name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        shell: powershell
        run: |
          docker build -t my-image-name:latest -f Dockerfile .

      - name: Remove Old Container
        shell: powershell
        run: |
          if (docker ps -a --format "{{.Names}}" | Select-String "^backend$") {
            docker rm -f backend
          }

      - name: Run Docker Container
        shell: powershell
        run: |
          docker run -d --name backend -p 3000:3000 my-image-name:latest

      - name: Show Docker Images
        shell: powershell
        run: |
          docker images

      - name: Show Docker Containers
        shell: powershell
        run: |
          docker ps
